spring:
  application:
    name: skill-project-tracker
  thymeleaf:
    cache: false

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:skilldb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${JDBC_DATABASE_URL}         # e.g., jdbc:postgresql://<host>:5432/<db>?sslmode=require
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update                # after first deploy, change to 'validate' + add Flyway/Liquibase
    show-sql: false
server:
  forward-headers-strategy: framework
