spring:
  application:
    name: skill-project-tracker

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/skilltracker
    username: skilluser
    password: skillpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  forward-headers-strategy: framework
