# default/local (your choice: H2 or local docker)
spring:
  application:
    name: skill-project-tracker

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:skilldb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

---
# PRODUCTION (Render) — uses env vars from Render dashboard
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  forward-headers-strategy: framework
