services:
  - type: web
    name: skill-project-tracker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: JDBC_DATABASE_URL
        sync: false
      - key: JDBC_DATABASE_USERNAME
        sync: false
      - key: JDBC_DATABASE_PASSWORD
        sync: false
